export enum NotificationType {
  LOGIN = 'login',
  PROPOSAL_RECEIVED = 'proposal_received',
  PROPOSAL_ACCEPTED = 'proposal_accepted',
  PROPOSAL_REJECTED = 'proposal_rejected',
  CONTRACT_CREATED = 'contract_created',
  CONTRACT_COMPLETED = 'contract_completed',
  CONTRACT_CANCELLED = 'contract_cancelled',
  MILESTONE_CREATED = 'milestone_created',
  MILESTONE_SUBMITTED = 'milestone_submitted',
  MILESTONE_APPROVED = 'milestone_approved',
  MILESTONE_REJECTED = 'milestone_rejected',
  PAYMENT_RECEIVED = 'payment_received',
  PAYMENT_SENT = 'payment_sent',
  PAYMENT_REFUNDED = 'payment_refunded',
  REVIEW_RECEIVED = 'review_received',
  MESSAGE_RECEIVED = 'message_received',
  DISPUTE_CREATED = 'dispute_created',
  DISPUTE_RESOLVED = 'dispute_resolved',
  WITHDRAWAL_REQUESTED = 'withdrawal_requested',
  WITHDRAWAL_PROCESSED = 'withdrawal_processed',
  WITHDRAWAL_COMPLETED = 'withdrawal_completed',
  JOB_POSTED = 'job_posted',
  JOB_COMPLETED = 'job_completed',
}
